baseURL = "https://note.strawbreey.com"
languageCode = "en-us"
title = "如沐春风"
theme = "kagome"
paginate = 7
copyright = "© 2021 <a href=\"https://github.com/miiiku/hugo-theme-kagome\">kagome</a>."
hasCJKLanguage = true

# 作者信息
[author]
  name = "strawbreey"
  email = "strawbreey@qq.com"
  description = "strawbreey"
  avatar = "/favicon.png"

# 菜单/导航栏
[menu]
  # 顶部导航栏
  [[menu.main]]
    identifier = "/"
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "POSTS"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/message"
    name = "MESSAGE"
    url = "/message"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "LINK"
    url = "/link"
    weight = 4
  
  # 底部社交图标
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/strawbreey"
    weight = 1
  [[menu.social]]
    identifier = "weibo"
    name = "weibo"
    url = "https://weibo.com/u/5561168966"
    weight = 4

# URL格式
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  files = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# 主题相关配置项
[params]
  keywords = ['theme', 'kagome']
  description = ""
  mainSections = ["posts"]
  # 国内备案号
  beian = ""
  # TOC目录出现字符长度限制
  toc_show_len = 300

  [params.analytics]
    baidu = ""

  [params.widget]
    # 相关文章推荐数量
    articles_count = 6
    # 分类相关显示数量
    categories_count = 6
    # 标签相关显示数量
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
